### ISSUE TITLE
Autoupdate werkt niet naar behoren

### ISSUE THREAD

**Issue by Moopey1** [exec-code/exec-code.github.io#1]
Wanneer je een spatie toevoegt aan een functie die een string console logt zoals hier: **test('Hoi!', ' Danny');**
kreeg ik het volgende resultaat: **'Hoi!Danny'**.

Autoupdate pikte dat niet op en ik moest op de re-run knop klikken op het gewenste resultaat te krijgen. 

(Ik heb echt geen idee hoe een issue er normaal uit ziet maar ik hoor graag hoe ik het anders kan doen.)

**Comment by Danny-Engelman** [comment]
Fixed: https://exec-code.github.io/
