### ISSUE TITLE
terminal verschijnt 2 keer op scherm

### ISSUE THREAD

**Issue by Moopey1** [exec-code/exec-code.github.io#2]
Als er een aanpassing gedaan word in de broncode van exec-code (bijvoorbeeld: tussen `<code></code>` een nieuwe opdracht uitschrijven) , verschijnt de terminal 2 keer. 
Dit is op te lossen door de pagina te herladen.

Ik wilde deze code aanpassen: 
```
<code>
            // console.log je naam zoals hieronder weergegeven
console.log('Hello World!');
            </code>
```
Toen ik console.log naar links opschoof, verscheen de terminal 2 keer.

**Comment by Danny-Engelman** [comment]
Fixed: https://exec-code.github.io/

Op een beetje dirty manier met meerdere ``setTimeout`` statements

_Als het niet kan zoals het moet dan moet het maar zoals het kan_
